# Configure latexmkrc: https://mg.readthedocs.io/latexmk.html
$dvi_previewer  = 'start xdvi -watchfile 1.5';
$ps_previewer   = 'start gv --watch';
$pdf_previewer  = 'start evince';
$clean_ext      = 'bbl nav out snm blg 